name: universal_week_calendar
description: A customizable horizontal week calendar widget that works with any state management.
version: 0.1.1
homepage: "https://pub.dev/packages/universal_week_calendar"
documentation: "https://github.com/Prashant1125/universal_week_calendar/blob/main/README.md"
repository: "https://github.com/Prashant1125/universal_week_calendar.git"
topics:
  - calendar
  - ui
  - date
  - week
  - flutter-widget

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
